package: community.lazycat.app.qd
version: 2025.1.29
name: QD
description: "一个 HTTP 定时任务自动执行 Web 框架"
min_os_version: "1.5.0"
homepage: https://github.com/qd-today/qd
author: qd-today
locales:
  zh:
    name: QD
    description: "一个 HTTP 定时任务自动执行 Web 框架"
  en:
    name: QD
    description: "An HTTP-based scheduled task automation web framework"
